Repository bazelbuild/rules_k8s, pull requests merged in 2018-10, with the labels that each got.

#186 update rules docker pin
  WORKSPACE
Labels: approved, lgtm, size/XS

#187 Allow project override
  images/gcloud-bazel/Makefile
Labels: approved, lgtm, size/XS

#196 Use kubectl describe foo name
  examples/hellogrpc/e2e-test.sh
  examples/hellohttp/e2e-test.sh
  examples/todocontroller/e2e-test.sh
  k8s/describe.sh.tpl
Labels: approved, lgtm, size/L

#193 Add logic to generate bazel + gcloud container using rules_docker
  .bazelci/presubmit.yml
  WORKSPACE
  images/gcloud-bazel/BUILD.bazel
  images/gcloud-bazel/Dockerfile
  images/gcloud-bazel/sources.list
  test-e2e.sh
Labels: approved, lgtm, needs-ok-to-test, size/L

#205 update pin to base images docker and rules docker
  WORKSPACE
Labels: approved, lgtm, size/S

#206 Add new kubectl toolchain rule
  k8s/k8s.bzl
  toolchains/kubectl/BUILD
  toolchains/kubectl/kubectl_toolchain.bzl
Labels: approved, lgtm, size/M

#204 Propagate arguments for implicit attributes to instantiated rules
  examples/todocontroller/BUILD
  examples/todocontroller/py/BUILD
  k8s/object.bzl
Labels: approved, size/M

#208 Use build id and repo name in namespace to uniquify
  .bazelrc
  WORKSPACE
  examples/hellogrpc/e2e-test.sh
  examples/hellohttp/e2e-test.sh
  examples/todocontroller/e2e-test.sh
  print-workspace-status.sh
  test-e2e.sh
Labels: approved, lgtm, size/L
