Repository bazelbuild/rules_k8s, pull requests merged in 2018-11, with the labels that each got.

#210 Kubectl via toolchains
  k8s/apply.sh.tpl
  k8s/create.sh.tpl
  k8s/delete.sh.tpl
  k8s/describe.sh.tpl
  k8s/k8s.bzl
  k8s/object.bzl
  k8s/replace.sh.tpl
  toolchains/kubectl/BUILD
Labels: approved, lgtm, size/M

#211 Adding contributors and reviewers
  CONTRIBUTORS
  OWNERS
Labels: approved, lgtm, size/XS

#216 Sprinkle some sleeps to try and improve e2e flakiness
  examples/hellogrpc/e2e-test.sh
  examples/hellohttp/e2e-test.sh
  examples/todocontroller/e2e-test.sh
Labels: approved, size/S

#222 Disabling controller e2e test till it is less flakey
  test-e2e.sh
Labels: lgtm, size/XS

#212 kubectl via toolchains (continued)
  k8s/k8s.bzl
  toolchains/kubectl/BUILD
  toolchains/kubectl/BUILD.tpl
  toolchains/kubectl/kubectl_configure.bzl
Labels: approved, size/M

#218 Remove kubectl toolchain execution platform constraint
  toolchains/kubectl/BUILD
Labels: ok-to-test, size/S

#217 Use gcloud builds, and :latest-$USER
  images/gcloud-bazel/Makefile
Labels: approved, lgtm, size/XS

#224 Arbitrary args for kubectl
  README.md
  examples/hellohttp/e2e-test.sh
  examples/hellohttp/java/BUILD
  k8s/apply.sh.tpl
  k8s/create.sh.tpl
  k8s/delete.sh.tpl
  k8s/describe.sh.tpl
  k8s/object.bzl
  k8s/replace.sh.tpl
Labels: approved, lgtm, size/M

#226 Kubectl via toolchains (documentation)
  README.md
  toolchains/kubectl/README.md
Labels: approved, lgtm, size/M

#203 Update protobuf rules for examples
  WORKSPACE
  examples/hellogrpc/cc/client/BUILD
  examples/hellogrpc/cc/server/BUILD
  examples/hellogrpc/go/client/BUILD
  examples/hellogrpc/go/server/BUILD
  examples/hellogrpc/go/server/main.go
  examples/hellogrpc/java/client/BUILD
  examples/hellogrpc/java/server/BUILD
  examples/hellogrpc/proto/BUILD
  examples/hellogrpc/py/client/BUILD
  examples/hellogrpc/py/requirements.txt
  examples/hellogrpc/py/server/BUILD
  examples/hellogrpc/py/server/server.py
Labels: approved, lgtm, size/L

#230 buildifier for objects.bzl
  k8s/object.bzl
Labels: approved, lgtm, size/XL

#229 Enable building kubectl hermetically as part of toolchain setup
  k8s/k8s.bzl
  k8s/object.bzl
  toolchains/kubectl/BUILD
  toolchains/kubectl/BUILD.path.tpl
  toolchains/kubectl/BUILD.target.tpl
  toolchains/kubectl/kubectl_configure.bzl
  toolchains/kubectl/kubectl_toolchain.bzl
Labels: approved, lgtm, size/L

#200 Add resolver to k8s_defaults
  README.md
  k8s/with-defaults.bzl
Labels: approved, lgtm, ok-to-test, size/S

#237 Update toolchain docs
  README.md
  WORKSPACE
  k8s/k8s.bzl
  k8s/object.bzl
  toolchains/kubectl/README.md
  toolchains/kubectl/kubectl_configure.bzl
  toolchains/kubectl/kubectl_toolchain.bzl
Labels: approved, lgtm, size/L

#236 update flask version to remove security warning
  examples/hellohttp/py/requirements.txt
Labels: approved, lgtm, size/XS
