Repository bazelbuild/rules_k8s, pull requests merged in 2018-06, with the labels that each got.

#152 fix hellogrpc/py examples by adding dependency
  examples/hellogrpc/py/requirements.txt
  examples/hellogrpc/py/server/BUILD
Labels: needs-ok-to-test, size/XS

#153 Create root-level OWNERS file
  OWNERS
Labels: needs-ok-to-test, size/S

#154 Add support options to README.md
  README.md
Labels: needs-ok-to-test, size/M

#155 Create a test-e2e.sh script which prow can run
  .gitignore
  examples/hellogrpc/e2e-test.sh
  examples/hellohttp/BUILD
  examples/hellohttp/e2e-test.sh
  examples/hellohttp/service.yaml
  test-e2e.sh
Labels: approved, needs-ok-to-test, size/L
