Repository bazelbuild/rules_k8s, pull requests merged in 2018-07, with the labels that each got.

#156 Create gcloud-bazel image for running e2e tests
  images/gcloud-bazel/BUILD.bazel
  images/gcloud-bazel/Dockerfile
  images/gcloud-bazel/Makefile
  images/gcloud-bazel/bazel.pub.gpg
  images/gcloud-bazel/cloudbuild.yaml
  images/gcloud-bazel/gcloud.pub.gpg
  images/gcloud-bazel/sources.list
  test-e2e.sh
Labels: approved, needs-ok-to-test, size/L

#159 remove Travis CI in favor of Prow
  .travis.yml
  README.md
Labels: approved, size/M

#157 switch from native.git_repository to external git_repository
  README.md
  WORKSPACE
  k8s/k8s.bzl
Labels: approved, size/S

#148 Support kubectl --user
  k8s/apply.sh.tpl
  k8s/create.sh.tpl
  k8s/delete.sh.tpl
  k8s/describe.sh.tpl
  k8s/object.bzl
  k8s/replace.sh.tpl
  k8s/with-defaults.bzl
Labels: size/M

#158 pass visibility into k8s commands
  k8s/object.bzl
Labels: approved, size/S

#163 hotfix: upgrade gunicorn version for fixing vulnerability
  examples/hellohttp/py/requirements.txt
Labels: approved, size/XS

#138 Adds 'context' parameter to k8s_object
  WORKSPACE
  k8s/apply.sh.tpl
  k8s/create.sh.tpl
  k8s/delete.sh.tpl
  k8s/describe.sh.tpl
  k8s/object.bzl
  k8s/replace.sh.tpl
  k8s/with-defaults.bzl
Labels: approved, size/L

#162 Add --allow_unused_images resolver flag (#161)
  k8s/object.bzl
  k8s/resolve.sh.tpl
  k8s/resolver.py
Labels: approved, lgtm, size/S

#144 Use the correct rule for k8s_service in hellogrpc service.
  examples/hellogrpc/BUILD
Labels: approved, size/XS

#168 Use /usr/bin/env bash for more portable shebang lines
  examples/hellogrpc/cc/server/edit.sh
  examples/hellogrpc/e2e-test.sh
  examples/hellogrpc/go/server/edit.sh
  examples/hellogrpc/java/server/edit.sh
  examples/hellogrpc/py/server/edit.sh
  examples/hellohttp/e2e-test.sh
  examples/hellohttp/go/edit.sh
  examples/hellohttp/java/edit.sh
  examples/hellohttp/nodejs/edit.sh
  examples/hellohttp/py/edit.sh
  examples/todocontroller/e2e-test.sh
  examples/todocontroller/py/edit.sh
  k8s/apply.sh.tpl
  k8s/create.sh.tpl
  k8s/delete.sh.tpl
  k8s/describe.sh.tpl
  k8s/replace.sh.tpl
  k8s/resolve-all.sh.tpl
  k8s/resolve.sh.tpl
  k8s/reverse.sh.tpl
  test-e2e.sh
Labels: approved, size/M

#170 Unlock extra actions if "context" attribute is set
  k8s/object.bzl
Labels: approved, size/XS

#169 Fix a typo: s/usre/user/
  k8s/object.bzl
Labels: approved, size/XS

#166 Add user and context attrs to README.md
  README.md
Labels: approved, size/M
