Repository bazelbuild/rules_k8s, pull requests merged in 2018-12, with the labels that each got.

#239 adding license for toolchain BUILD file
  .bazelci/presubmit.yml
  WORKSPACE
  toolchains/kubectl/BUILD
Labels: approved, size/M

#241 update pin to rules_proto
  .bazelci/presubmit.yml
  WORKSPACE
Labels: approved, lgtm, size/S

#243 use latest release of protobuf
  WORKSPACE
Labels: approved, lgtm

#247 test only a few things on mac, its flaky
  .bazelci/presubmit.yml
Labels: approved, size/XS

#251 Documentation & refactoring for custom kubectl from source
  WORKSPACE
  k8s/k8s.bzl
  toolchains/kubectl/README.md
  toolchains/kubectl/defaults.bzl
  toolchains/kubectl/kubectl_configure.bzl
Labels: approved, lgtm, size/L

#253 Allow downloading prebuilt binary in kubectl toolchain
  toolchains/kubectl/README.md
  toolchains/kubectl/kubectl_configure.bzl
  toolchains/kubectl/kubectl_toolchain.bzl
Labels: approved, feature request, lgtm, size/M

#250 Local e2e tests
  examples/hellogrpc/e2e-test.sh
  examples/hellohttp/BUILD
  examples/hellohttp/deployment.jsonnet
  examples/hellohttp/deployment.yaml
  examples/hellohttp/e2e-test.sh
  examples/hellohttp/go/BUILD
  examples/hellohttp/java/BUILD
  examples/hellohttp/nodejs/BUILD
  examples/hellohttp/py/BUILD
  examples/todocontroller/e2e-test.sh
  examples/util.sh
  test-e2e-local.sh
  test-e2e.sh
Labels: approved, feature request, size/L

#254 Add a doc to run e2e tests locally.
  README.md
  examples/README.md
Labels: approved, lgtm, size/M
