Repository bazelbuild/rules_k8s, pull requests merged in 2019-04, with the labels that each got.

#300 Return providers instead of struct from rule impl functions
  k8s/object.bzl
  k8s/objects.bzl
Labels: approved, lgtm, size/M

#301 Fix incompatible issue
  WORKSPACE
  k8s/object.bzl
  k8s/objects.bzl
  third_party/com_github_grpc_grpc/BUILD
  third_party/com_github_grpc_grpc/bcc9f308c6.patch
Labels: approved, lgtm, size/M

#302 update protobuf pin
  WORKSPACE
Labels: approved, size/S

#310 Update go to 0.18.2 & disable go targets on Ubuntu 14.04
  .bazelci/presubmit.yml
  WORKSPACE
  k8s/k8s.bzl
Labels: approved, lgtm, size/S

#313 Update rules_jsonnet pin
  .bazelci/presubmit.yml
  WORKSPACE
Labels: approved, lgtm, size/S

#315 use ubuntu18.04 in presubmit
  .bazelci/presubmit.yml
Labels: approved, lgtm, size/S

#317 Don't test on Ubuntu 14.04
  .bazelci/presubmit.yml
Labels: approved, ok-to-test, size/S

#323 Update renovate to run weekly
  renovate.json
Labels: approved, lgtm, size/XS

#324 pull rules_go uniformly in k8s.bzl vs WORKSPACE
  k8s/k8s.bzl
Labels: approved, lgtm, size/XS

#325 Update jsonnet dependency
  WORKSPACE
Labels: approved, lgtm, size/XS
