Repository bazelbuild/rules_k8s, pull requests merged in 2019-05, with the labels that each got.

#327 Allow kubeconfig in k8s_defaults and .delete rules
  examples/hellogrpc/e2e-test.sh
  k8s/delete.sh.tpl
  k8s/with-defaults.bzl
Labels: approved, lgtm, ok-to-test, size/S

#335 Port internal change of marking python binary versions explicitly
  examples/hellogrpc/BUILD
  examples/hellogrpc/e2e-test.sh
  examples/hellogrpc/py/client/BUILD
  examples/hellohttp/BUILD
  k8s/BUILD
Labels: approved, lgtm, size/S

#339 Update rules_go to 0.18.5
  WORKSPACE
Labels: approved, lgtm, size/XS

#337 Fixing kubectl toolchain docs
  toolchains/kubectl/README.md
Labels: approved, lgtm, size/XS

#344 Add a namespace garbage collector.
  examples/BUILD
  examples/e2e_gc.py
  test-e2e.sh
Labels: approved, lgtm, size/M

#306 using python_version to try issues with 0.25.0rc1
  .bazelrc
  WORKSPACE
  k8s/BUILD
Labels: approved, lgtm, size/S

#343 Add make resolve support for images.
  .bazelrc
  README.md
  examples/hellogrpc/cc/server/BUILD
  k8s/object.bzl
Labels: approved, lgtm, ok-to-test, size/XS

#342 Add support for select statement for k8s_objects.
  README.md
  examples/hellogrpc/BUILD
  k8s/objects.bzl
Labels: approved, lgtm, ok-to-test, size/M

#352 Update rules_proto
  WORKSPACE
Labels: approved, lgtm, size/XS

#353 Update dependency on grpc
  WORKSPACE
Labels: approved, lgtm, size/XS
