Repository bazelbuild/rules_k8s, pull requests merged in 2019-07, with the labels that each got.

#382 Update README.md
  README.md
Labels: approved, lgtm, size/S

#389 Update OWNERS
  OWNERS
Labels: approved, lgtm, size/XS

#388 Update CODEOWNERS
  CODEOWNERS
Labels: approved, lgtm, size/XS

#393 remove base_images_docker and update rules_docker
  WORKSPACE
  images/gcloud-bazel/BUILD
Labels: approved, lgtm, size/M

#402 Update Flask version
  examples/hellohttp/py/requirements.txt
Labels: approved, lgtm, size/XS

#407 Fix rules_python workspace name
  WORKSPACE
Labels: approved, lgtm, size/XS
