Repository bazelbuild/rules_k8s, pull requests merged in 2019-03, with the labels that each got.

#274 Fix buildifier 0.22.0 lint warnings
  .bazelci/presubmit.yml
  k8s/object.bzl
  k8s/objects.bzl
  test-e2e.sh
  toolchains/kubectl/kubectl_configure.bzl
Labels: approved, lgtm, size/M

#273 Update rules_go to 0.17.0
  WORKSPACE
Labels: approved, size/XS

#275 Re-enable buildifier with specific warnings turned off
  .bazelci/presubmit.yml
  test-e2e.sh
Labels: approved, size/S

#276 Explicitly import latest version of grpc
  WORKSPACE
Labels: approved, lgtm, size/XS

#284 [DOCS] update the load command for container_repositories
  README.md
Labels: approved, lgtm, size/XS

#286 Run renovate once daily instead of all the time
  renovate.json
Labels: approved, lgtm, size/XS

#246 Add a "substitutions" parameter to operations
  README.md
  examples/hellogrpc/BUILD
  examples/hellogrpc/service.yaml
  k8s/object.bzl
Labels: approved, feature request, lgtm, size/M

#287 rules_k8s: Support passing in a kubeconfig file
  README.md
  examples/hellogrpc/BUILD
  examples/hellogrpc/e2e-test.sh
  k8s/apply.sh.tpl
  k8s/create.sh.tpl
  k8s/object.bzl
Labels: approved, lgtm, ok-to-test, size/M

#289 Update deps for --incompatible_remove_old_python_version_api
  WORKSPACE
Labels: approved, lgtm, size/M

#297 Increase wait for hellohttp load balancer service to come up
  examples/hellohttp/e2e-test.sh
  examples/hellohttp/py/server.py
  examples/hellohttp/service.yaml
  test-e2e.sh
Labels: approved, size/S

#296 images is not required on k8s_object
  README.md
Labels: approved, lgtm, ok-to-test, size/XS
