Repository bazelbuild/rules_k8s, pull requests merged in 2019-02, with the labels that each got.

#262 Update OWNERS
  OWNERS
Labels: approved, lgtm, size/XS

#263 Add buildifier to buildkite and fix lint issues.
  .bazelci/presubmit.yml
  BUILD
  WORKSPACE
  examples/BUILD
  examples/hellogrpc/BUILD
  examples/hellogrpc/cc/client/BUILD
  examples/hellogrpc/cc/server/BUILD
  examples/hellogrpc/go/client/BUILD
  examples/hellogrpc/go/server/BUILD
  examples/hellogrpc/java/client/BUILD
  examples/hellogrpc/java/server/BUILD
  examples/hellogrpc/proto/BUILD
  examples/hellogrpc/py/BUILD
  examples/hellogrpc/py/client/BUILD
  examples/hellogrpc/py/server/BUILD
  examples/hellohttp/BUILD
  examples/hellohttp/go/BUILD
  examples/hellohttp/java/BUILD
  examples/hellohttp/nodejs/BUILD
  examples/hellohttp/py/BUILD
  examples/todocontroller/BUILD
  examples/todocontroller/py/BUILD
  images/gcloud-bazel/BUILD
  k8s/BUILD
  toolchains/kubectl/BUILD
  toolchains/kubectl/defaults.bzl
  toolchains/kubectl/kubectl_configure.bzl
Labels: approved, size/L

#265 Add adopters section
  README.md
Labels: approved, lgtm, size/XS

#267 Add more adopters
  README.md
Labels: approved, lgtm, size/XS

#268 Fix --incompatible_disallow_dict_plus
  .gitignore
  WORKSPACE
  k8s/object.bzl
Labels: approved, lgtm, size/M
