Repository bazelbuild/rules_k8s, pull requests merged in 2019-11, with the labels that each got.

#463 Migrate maven_jar usage to maven_install. maven_jar will be removed from Bazel 2.0.
  WORKSPACE
Labels: approved, lgtm, size/S

#468 Update rules_go version along with grpc dependencies fix
  examples/hellogrpc/proto/BUILD
  k8s/k8s.bzl
Labels: approved, lgtm, size/S

#470 Update README for v0.3.1
  README.md
Labels: approved, lgtm, size/XS

#462 Remove PY2 notice from the README
  README.md
Labels: approved, lgtm, ok-to-test, size/S
