Repository bazelbuild/rules_k8s, pull requests merged in 2019-10, with the labels that each got.

#432 update rules_docker to pin after fixes for bazel head
  k8s/k8s.bzl
Labels: approved, lgtm, ok-to-test, size/XS

#434 Implement image publishing in resolver
  k8s/go/cmd/resolver/BUILD
  k8s/go/cmd/resolver/resolver.go
  k8s/object.bzl
Labels: approved, lgtm, size/L

#435 Complete the implementation of the Go resolver
  WORKSPACE
  examples/hellohttp/static-deployment.yaml
  k8s/go/cmd/resolver/BUILD
  k8s/go/cmd/resolver/resolver.go
  k8s/go/cmd/resolver/resolver_test.go
  k8s/k8s.bzl
  k8s/k8s_go_deps.bzl
  k8s/object.bzl
Labels: approved, lgtm, size/L

#436 Update README for release v0.2
  README.md
Labels: approved, lgtm, size/S

#441 depset transitive expects sequence of depsets
  k8s/object.bzl
Labels: approved, lgtm, size/XS

#444 Support resolving YAML streams in Go resolver
  k8s/go/cmd/resolver/resolver.go
  k8s/go/cmd/resolver/resolver_test.go
Labels: approved, lgtm, size/L

#445 Add resolver test case for empty YAML doc
  k8s/go/cmd/resolver/resolver_test.go
Labels: approved, lgtm, size/XS

#446 Go resolver should return strings as is on any kind of error
  k8s/go/cmd/resolver/resolver.go
Labels: approved, lgtm, size/S

#447 Comment why the string resolver ignores all errors
  k8s/go/cmd/resolver/resolver.go
Labels: approved, lgtm, size/XS

#453 update grpc + protobuf + go
  .bazelci/presubmit.yml
  WORKSPACE
  examples/hellogrpc/e2e-test.sh
  examples/hellohttp/e2e-test.sh
  k8s/k8s.bzl
  test-e2e.sh
  third_party/build_stack_rules_proto/BUILD
  third_party/build_stack_rules_proto/stackb.patch
  third_party/com_github_grpc_grpc/bcc9f308c6.patch
Labels: approved, lgtm, size/L

#458 Update bazel_skylib + rules_go
  k8s/k8s.bzl
Labels: approved, lgtm, size/S

#459 Remove python resolver
  k8s/BUILD
  k8s/k8s.bzl
  k8s/object.bzl
  k8s/resolver.py
  k8s/resolver_test.py
Labels: approved, lgtm, size/L

#460 Update README for v0.3 release
  README.md
Labels: approved, lgtm, size/XS

#461 Make //k8s:reverser and //k8s:stamper PY2 and PY3 compatible
  k8s/BUILD
  k8s/k8s.bzl
  k8s/reverser.py
Labels: approved, lgtm, ok-to-test, size/S
