Repository bazelbuild/rules_k8s, pull requests merged in 2020-04, with the labels that each got.

#544 Fix the documentation bug on stamping
  README.md
Labels: approved, lgtm, ok-to-test, size/XS

#545 Fix version used in README to v0.4 (current latest)
  README.md
Labels: approved, lgtm, ok-to-test, size/XS

#543 Modify description of k8s_object to be more explicit
  README.md
Labels: approved, lgtm, ok-to-test, size/XS

#541 fix encoding error
  k8s/reverser.py
Labels: approved, ok-to-test, size/XS

#546 Add descriptions on `resolver_args`
  README.md
Labels: approved, lgtm, ok-to-test, size/XS

#549 Install an old version of bazel in gcloud-bazel.
  images/gcloud-bazel/Dockerfile
  images/gcloud-bazel/Makefile
  images/gcloud-bazel/cloudbuild.yaml
Labels: approved, lgtm, size/M

#548 Update io_bazel_rules_go pin
  WORKSPACE
  k8s/k8s.bzl
Labels: approved, lgtm, size/S

#550 Correct typos:
  images/gcloud-bazel/Dockerfile
  images/gcloud-bazel/cloudbuild.yaml
Labels: approved, lgtm, size/XS

#552 Update owners
  CODEOWNERS
  OWNERS
Labels: approved, lgtm, size/XS
