Repository bazelbuild/rules_k8s, pull requests merged in 2020-02, with the labels that each got.

#518 Update build_stack_rules_proto commit + patch file
  WORKSPACE
  third_party/build_stack_rules_proto/stackb.patch
Labels: approved, lgtm, size/M

#521 Make rules_k8s compatible with --incompatible_load_proto_rules_from_bzl
  examples/hellogrpc/proto/BUILD
Labels: approved, lgtm, ok-to-test, size/XS

#531 Mark stamper and reverser as python 3
  .bazelrc
  k8s/BUILD
  k8s/reverser.py
  k8s/stamper.py
Labels: approved, lgtm, size/S
