Repository bazelbuild/rules_k8s, pull requests merged in 2020-06, with the labels that each got.

#560 clarify resolver in readme
  README.md
Labels: approved, ok-to-test, size/XS

#566 Add some debugging info
  WORKSPACE
  examples/hellogrpc/e2e-test.sh
  examples/hellohttp/e2e-test.sh
  print-workspace-status.sh
Labels: approved, lgtm, size/S

#565 Use substituted template for delete action
  k8s/object.bzl
Labels: approved, ok-to-test, size/S

#570 Refactor e2e testing
  .bazelrc
  .bazelversion
  .gitignore
  WORKSPACE
  examples/BUILD
  examples/e2e_gc.py
  examples/hellogrpc/BUILD
  examples/hellogrpc/cc/client/main.cc
  examples/hellogrpc/cc/server/edit.sh
  examples/hellogrpc/e2e-test.sh
  examples/hellogrpc/go/server/BUILD
  examples/hellogrpc/go/server/edit.sh
  examples/hellogrpc/java/server/edit.sh
  examples/hellogrpc/proto/BUILD
  examples/hellogrpc/py/client/BUILD
  examples/hellogrpc/py/requirements.txt
  examples/hellogrpc/py/server/BUILD
  examples/hellogrpc/py/server/edit.sh
  examples/hellogrpc/py/server/server.py
  examples/hellohttp/BUILD
  examples/hellohttp/e2e-test.sh
  examples/hellohttp/go/BUILD
  examples/hellohttp/go/edit.sh
  examples/hellohttp/java/edit.sh
  examples/hellohttp/nodejs/edit.sh
  examples/hellohttp/py/BUILD
  examples/hellohttp/py/edit.sh
  examples/hellohttp/py/requirements.txt
  examples/hellohttp/service.yaml
  examples/todocontroller/BUILD
  examples/todocontroller/deployment.yaml
  examples/todocontroller/e2e-test.sh
  examples/todocontroller/example.yaml
  examples/todocontroller/joined.yaml
  examples/todocontroller/py/BUILD
  examples/todocontroller/py/controller.py
  examples/todocontroller/py/requirements.txt
  examples/todocontroller/todo.yaml
  examples/util.sh
  hack/print-workspace-status.sh
  images/gcloud-bazel/Dockerfile
  k8s/k8s.bzl
  print-workspace-status.sh
  requirements.txt
  test-e2e-local.sh
  test-e2e.sh
Labels: approved, size/XXL

#571 Build all targets and use .append() .extend() instead of +=
  images/gcloud-bazel/BUILD
  k8s/object.bzl
  k8s/objects.bzl
  k8s/with-defaults.bzl
Labels: approved, lgtm, size/M

#578 Keep approvers/reviewers up to date.
  CODEOWNERS
  OWNERS
Labels: approved, lgtm, size/S

#579 Remove python examples.
  WORKSPACE
  examples/hellogrpc/e2e-test.sh
  examples/hellogrpc/proto/BUILD
  examples/hellogrpc/py/BUILD
  examples/hellogrpc/py/client/BUILD
  examples/hellogrpc/py/client/client.py
  examples/hellogrpc/py/server/BUILD
  examples/hellogrpc/py/server/edit.sh
  examples/hellogrpc/py/server/server.py
  examples/hellohttp/py/BUILD
  examples/hellohttp/py/edit.sh
  examples/hellohttp/py/server.py
  requirements.txt
  test-e2e.sh
Labels: approved, lgtm, size/L

#577 Drop cc examples.
  WORKSPACE
  examples/hellogrpc/cc/client/BUILD
  examples/hellogrpc/cc/client/main.cc
  examples/hellogrpc/cc/client/simple.cc
  examples/hellogrpc/cc/client/simple.h
  examples/hellogrpc/cc/server/BUILD
  examples/hellogrpc/cc/server/edit.sh
  examples/hellogrpc/cc/server/main.cc
  examples/hellogrpc/e2e-test.sh
  examples/hellogrpc/proto/BUILD
  examples/hellohttp/e2e-test.sh
  test-e2e.sh
Labels: approved, size/L
