Repository bazelbuild/rules_k8s, pull requests merged in 2020-01, with the labels that each got.

#500 propagate error message up the stack
  k8s/go/cmd/resolver/resolver.go
Labels: approved, lgtm, ok-to-test, size/XS

#496 Update rules_docker pin
  .gitignore
  WORKSPACE
  examples/hellohttp/nodejs/BUILD
  examples/yarn.lock
  k8s/k8s.bzl
Labels: approved, lgtm, ok-to-test, size/M

#510 update rules_docker & other deps
  WORKSPACE
  examples/hellogrpc/java/client/HelloClient.java
  examples/yarn.lock
  k8s/k8s.bzl
  third_party/build_stack_rules_proto/stackb.patch
Labels: approved, lgtm, size/L
