Repository bazelbuild/rules_k8s, pull requests merged in 2021-04, with the labels that each got.

#650 Remove broken HTTP E2E test
  .bazelci/presubmit.yml
  examples/deployment.libsonnet
  examples/hellogrpc/deployment.yaml
  examples/hellohttp/deployment.yaml
  examples/hellohttp/static-deployment.yaml
  examples/stamping/deployment.yaml
  test-e2e.sh
Labels: approved, lgtm, size/M

#639 Add support for Bazel 3.0.0
  .bazelci/presubmit.yml
  .bazelversion
  WORKSPACE
  k8s/k8s.bzl
  k8s/k8s_go_deps.bzl
Labels: approved, lgtm, ok-to-test, size/L

#655 Fix e2e tests
  .bazelci/presubmit.yml
  .bazelversion
  WORKSPACE
  examples/hellogrpc/e2e-test.sh
  examples/hellohttp/e2e-test.sh
  examples/util.sh
  k8s/k8s.bzl
  k8s/k8s_go_deps.bzl
  test-e2e.sh
Labels: approved, lgtm, size/L

#626 fix gazelle
  BUILD
  WORKSPACE
  k8s/go/cmd/resolver/BUILD
Labels: approved, lgtm, ok-to-test, size/S

#635 Add Tink AB to list of adopters
  README.md
Labels: approved, lgtm, ok-to-test, size/XS

#634 Allow rules_k8s targets to be invoked within other Bazel targets
  k8s/apply.sh.tpl
  k8s/create.sh.tpl
  k8s/delete.sh.tpl
  k8s/describe.sh.tpl
  k8s/diff.sh.tpl
  k8s/replace.sh.tpl
  k8s/resolve-all.sh.tpl
  k8s/resolve.sh.tpl
Labels: approved, lgtm, ok-to-test, size/M

#628 Resolver library
  k8s/go/cmd/resolver/BUILD
  k8s/go/cmd/resolver/resolver.go
  k8s/go/pkg/resolver/BUILD.bazel
  k8s/go/pkg/resolver/resolver.go
  k8s/go/pkg/resolver/resolver_test.go
Labels: approved, lgtm, ok-to-test, size/XXL

#644 Add kubectl toolchain for linux arm64
  k8s/k8s.bzl
  toolchains/kubectl/BUILD
  toolchains/kubectl/README.md
Labels: approved, lgtm, ok-to-test, size/S

#656 Update rules_docker
  .bazelci/presubmit.yml
  WORKSPACE
  k8s/k8s.bzl
  k8s/k8s_go_deps.bzl
Labels: approved, lgtm, size/L
