Repository bazelbuild/rules_k8s, pull requests merged in 2022-06, with the labels that each got.

#699 Support 5.2.0
  .bazelrc
  .bazelversion
  WORKSPACE
  examples/BUILD
  examples/hellogrpc/deployment_test.py
  examples/hellogrpc/e2e-test.sh
  examples/hellogrpc/go/server/main.go
  examples/hellogrpc/java/client/BUILD
  examples/hellogrpc/java/server/BUILD
  examples/hellogrpc/proto/BUILD
  examples/hellogrpc/proto/simple.proto
  examples/hellohttp/deployment_test.py
  examples/hellohttp/e2e-test.sh
  examples/hellohttp/nodejs/BUILD
  examples/hellohttp/nodejs/server.js
  examples/stamping/BUILD
  examples/stamping/go/BUILD
  examples/stamping/substitution_test.py
  images/gcloud-bazel/Dockerfile
  images/gcloud-bazel/Makefile
  images/gcloud-bazel/bazel.list
  images/gcloud-bazel/bazel.pub.gpg
  k8s/BUILD
  k8s/k8s.bzl
  k8s/k8s_go_deps.bzl
  requirements.txt
Labels: size/L, approved

#700 Fix buildifier files
  .bazelci/presubmit.yml
  .bazelrc
  WORKSPACE
  examples/BUILD
  examples/hellogrpc/proto/BUILD
  examples/hellohttp/nodejs/BUILD
  examples/stamping/go/BUILD
  k8s/k8s.bzl
Labels: size/M, lgtm, approved

#701 Drop nodejs, java examples
  WORKSPACE
  examples/hellogrpc/java/client/BUILD
  examples/hellogrpc/java/client/HelloClient.java
  examples/hellogrpc/java/server/BUILD
  examples/hellogrpc/java/server/HelloServer.java
  examples/hellogrpc/java/server/edit.sh
  examples/hellogrpc/proto/BUILD
  examples/hellogrpc/proto/simple.proto
  examples/hellohttp/e2e-test.sh
  examples/hellohttp/go/BUILD
  examples/hellohttp/java/BUILD
  examples/hellohttp/java/Servlet.java
  examples/hellohttp/java/edit.sh
  examples/hellohttp/nodejs/BUILD
  examples/hellohttp/nodejs/edit.sh
  examples/hellohttp/nodejs/package.json
  examples/hellohttp/nodejs/server.js
  test-e2e.sh
  third_party/build_stack_rules_proto/BUILD
  third_party/build_stack_rules_proto/stackb.patch
Labels: size/XL, lgtm, approved

#702 Remove cc from WORKSPACE, gcloud-bazel/BUILD
  .bazelci/presubmit.yml
  WORKSPACE
  images/gcloud-bazel/BUILD
  test-e2e.sh
Labels: size/M, lgtm, approved

#703 Drop jsonnet complexity
  WORKSPACE
  examples/BUILD
  examples/container.libsonnet
  examples/deployment.libsonnet
  examples/hellogrpc/BUILD
  examples/hellogrpc/deployment.jsonnet
  examples/hellogrpc/go/server/BUILD
  examples/hellohttp/BUILD
  examples/hellohttp/deployment.jsonnet
  examples/yarn.lock
Labels: size/XL, lgtm, approved

#706 Delete unused .ci files
  .ci/rules_k8s.json
Labels: size/S, lgtm, approved

#707 Use common args
  k8s/object.bzl
Labels: size/XS, lgtm, approved

#673 Update multiple dependency versions.
  WORKSPACE
  k8s/k8s.bzl
  k8s/k8s_go_deps.bzl
Labels: size/M, lgtm, approved, ok-to-test
